## Topic modeling con Transfer learning (feature extraction) - domande di rinuncia agli studi

Le domande di rinuncia presentate dagli studenti contengono un campo "note" in cui è possibile inserire testo libero con i motivi dell'abbandono.

Il task è raggruppare in topic generali questi testi. Sfruttiamo NLP e i Transformers

In [1]:
#!pip install bertopic[all] sentence-transformers
#pip install tf-keras
##!pip install transformers torch sentencepiece

In [2]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Utente\PycharmProjects\Data_mining_UPO\data\p04domchi2.csv', header=None, names=["testo"], sep=';', encoding="latin-1")
texts = df["testo"].fillna("").astype(str).tolist()
print("Check una riga se funziona:", texts[0])
print("Check numero record:", len(df))

Check una riga se funziona: Impossibilità a proseguire gli studi
Check numero record: 3319

In [3]:
# Rimuovo duplicati e righe troppo corte + lowering
# No preprocessing complesso perché SBERT / BERTopic già gestiscono (pare) stopword e tokenizzazione; così sembra anche più facilmente replicabile
df = df.drop_duplicates(subset="testo")
df = df[df["testo"].str.split().str.len() > 2]
df["testo"] = df["testo"].str.lower()
texts = df["testo"].tolist()

texts

['impossibilità a proseguire gli studi',
 'cambio percorso accedemico',
 'indisponibilità a pagare la ii rata del corso',
 'esami propedeutici lingue',
 'mancata disponibilità economica.',
 'spett.le università, \ncon mio rammarico, mi vedo costretto a rinunciare al percorso di studi scelto a causa degli improrogabili impegni di lavoro che non mi permettono di studiare in maniera adeguata.\nringrazandovi, porgo i più\ncordiali saluti, \nc. ',
 'incompatibilità con impegni lavorativi.',
 "non riesco a conciliare l'impegno dello studio con la mia attività lavorativa",
 'motivi di lavoro',
 'sono malata da tanto. sono rimasta iscritta nella speranza che le cose migliorassero, ma non è andata così. le mie condizioni sono molto peggiorate e le prospettive ormai sono solo di peggioramento.\npertanto è arrivato il momento per me di abbandonare gli studi.\nvi ringrazio, cordiali saluti.',
 "a chi di competenza,\n\nbuongiorno,\n\npochi giorni dopo l'immatricolazione, ho ottenuto un contratto di lavoro all'estero. terminato il contratto, ho trovato un lavoro in italia, che fosse sufficientemente flessibile per permettere lo studio. l\x92attuale impiego ha rinnovi mensili e trimestrali: lavoro continuativamente da più di otto mesi. consultando diverse volte la segreteria, questo tipo di rinnovo pare non possa permettere di inoltrare la richiesta di studente part-time ed ottenere il dilazionamento degli studi su un arco di tempo maggiore. \nil motivo della domanda di chiusura è il seguente: avendo un lavoro part-time con rinnovi mensili e trimestrali, non posso sostenere i costi delle rate.\ngrazie dell\x92attenzione\n",
 "a malincuore devo rinunciare in quanto sono stata accettata alla scuola di specializzazione in medicina d'urgenza e emergenza e a quanto pare in italia le due iscrizioni sono incompatibili, nonostante siano due corsi totalmente affini",
 'mi manca un esame e ho bisogno di più tempo per preparalo, ad aprile mi si chiuderebbe comunque la carriera',
 'problemi di salute',
 'per problemi personali molto invalidanti non riesco più a proseguire la mia carriera universitaria.',
 "l'organizzazione di questo corso di laurea non incontra le mie esigenze e il mio percorso lavorativo",
 "non riesco a superare l'esame di spagnolo 2 dopo innumerevoli tentativi.",
 "rientro in inghilterra per motivi personali. ho lasciato l'università a novembre 2019 ma non sapevo come rinunciare formalmente.",
 'motivi di lavoro',
 'cambio facoltà per motivi professionali.',
 "motivo personale, ho trovato un lavoro e vorrei chiudere il mio percorso universitario oggi senza pagare la rata d'iscrizione",
 'impossibilitata a proseguire ',
 'inizio di una carriera lavorativa che rende impossibile la prosecuzione degli studi. ',
 "impossibilita' nel proseguimento del percorso universitario",
 'altri obiettivi e incapacità di sostenere le spese universitarie ',
 'motivi di salute grave',
 'decisione di intraprendere una carriera lavorativa ',
 'per motivi familiari e lavorativi non posso più proseguire la carriera universitaria ',
 'vorrei iscrivermi al regime part time con previsione di un percorso in 6 anni.\nin base al regolamento, questo percorso può essere chiesto solo al primo anno di corso, in quanto dal secondo è possibile chiedere solo un percorso in 4 anni.\ndevo quindi rinunciare al percorso in essere e ripartire da capo.\n',
 'rinuncia per motivi personali.\n',
 'iscrizione ad altro istituto di formazione',
 "incompatibilità degli studi con l'attività lavorativa full time",
 'il pessimo servizio di segreteria offerto da unipv',
 'mancata motivazione e passione per la facoltà scelta ',
 'questo corso non fa per me, non mi sento motivata a continuare e di conseguenza ho deciso di cambiare una volta per tutte.',
 'perdita di interesse verso il corso di laurea',
 'rinuncio agli studi del clacfa  perché ho intenzione di cambiare corso ed immatricolarmi a scienze motorie (iscrizione al bando fatta e tolc-f esito positivo).',
 'cambio corso di studi presso altra università',
 'perdita di motivazione ed interesse per il corso di studio.',
 'scelta del corso sbagliato',
 'impegnato con il lavoro e non più interessato al piano di studi scelto.',
 'non mi sento pronto a continuare gli studi',
 'io devi studiare in turchia perquesto motivo deve riunincare la domanda di chiusura io voglio studiare in turchia',
 "chiusura carriera ed iscrizione ad un'altra università",
 'impossibilità di studio ',
 'passaggio ad altro corso (infermieristica)',
 'inizio di una nuova laurea magistrale a settembre',
 'mancato interesse a continuare il corso',
 'non sono intenzionato a continuare con gli studi',
 'cambio percorso di studi',
 'motivi di salute ',
 'sto lavorando a tempo pieno e non riesco a seguire le lezioni, e di conseguenza a preparare gli esami. ',
 'inizio percorso lavorativo',
 'cambio di corso ',
 'nuova immatricolazione presso università telematica.',
 'problemi famigliari e di salute personali che purtroppo hanno richiesto molte energie psicofisiche.',
 'sono indietro con gli esami e non riesco più a mantenermi',
 'impossibilità di poter seguire il corso a causa di problemi personali.',
 'ho capito non essere il corso adatto a me, non ero felice del percorso scelto',
 'rinuncio per motivi economici, di salute, e per necessità di iniziare a lavorare.',
 'non ritengo sia la facoltà adatta a me.',
 'motivi personali e lavorativi.',
 'rinuncia agli studi',
 "frequenza tfa vi ciclo sostegno in un'altra università",
 'passaggio ad università telematica',
 "la didattica a distanza presenta troppi problemi e, in questo periodo di pandemia, non mi sento a mio agio con l'idea delle lezioni in presenza.",
 "distanza fisica dall'ateneo e motivi lavorativi",
 'riproverò il test per accedere al corso di studio di fisioterapia, è ciò che realmente mi interessa ',
 'non riesco a portare avanti il mio piano di studi + lavoro ',
 'non è il corso adatto a me',
 'lavoro e ambizioni differenti ',
 'buonasera, avendo iniziato a lavorare due anni fa, ho deciso di riscrivermi come studentessa lavoratrice.\ncordialmente,\ncaci martina',
 "scrizione ad un'altra università",
 'il corso da me scelto non è più conforme con ciò che desidero ottenere dal mio percorso di studi. ',
 "superato test in una facolta' piu' vicina al mio domicilio",
 "superato test altra facolta'",
 "cambio universita' piu' vicina a casa",
 'cambio facoltà più vicina ',
 'rinuncia allo studio',
 'ho iniziato a lavorare e dovrei iscrivermi ad un altra facoltà ',
 'iscrizione a un altro corso di laurea',
 'le spese sostenute per permettermi di proseguire sono oggi incompatibli con i tempi a me necessari.',
 'la malattia mi ha costretto ad abbandonare gli studi non appena li avevo intrapresi. se me ne sarà data la possibilità, vorrei reimmatricolarmi col prossimo anno accademico.',
 'inizio percorso lavorativo',
 'volontà di immatricolarsi presso altro ateneo ',
 "sono stata ammessa a un corso di laurea presso un'altra università che ritengo più indicato per la mia carriera lavorativa.",
 'rinuncia per cambiare indirizzo di studi ',
 'cambio di facoltà degli studi',
 'problematiche di tempo',
 'ho cambiato idea sul mio percorso di studio ',
 'abbandono per esigenze personali',
 'immatricolazione presso un altro ateneo',
 'cambio di facoltà ',
 'immatricolazione al corso di laurea in medicine and surgery - università di parma',
 'per poter intraprendere la carriera universitaria mi sono trasferito dal sud al nord per lavorare in modo da poter mantenermi, ma con lo stipendio che prendevo non riuscivo a sostenere sia le spese diciamo "normali" e nemmeno quelle extra. ho cercato di trovare un\'occupazione che mi permettesse sia di proseguire gli studi e sia di poter mantenere un tenore di vita sufficiente ma non sono riuscito, a malincuore sono dovuto quindi ritornare nella mia città natale. ',
 'per motivi lavorativi ',
 'distanza eccessiva da casa e mancato interesse per alcune materie ',
 'ammissione presso altro ateneo situato in lombardia per laurea magistrale',
 'i am an irish student currently enrolled in the harvey medical school. however due to the covid 19 pandemic, i have been unable to attend the harvey medical school in person and have been met with problems trying to relocate to italy. i am also finding unexpected difficulties with online learning due to living in a rural area with poor internet connections and frequent online interruptions. the online aspects have proven to be more difficult than i thought they would be. i have had trouble getting my documents here due to covid restrictions here in ireland. \ntherefore, i have made the difficult decision of withdrawing from the course for now, due to covid and the associated difficulties of the current pandemic. i intend to resit the imat and reapply to the harvey course in the future as soon as things return to a more normal state.\nthank you for all the help while i was here, with information and enquiries. i wish you all the best for the future and hope to re-enroll in the harvey course in the future.\nkindest regards,\nkumail abbas syed.',
 'motivi familiari e lavorativi.\n',
 'iscrizione a una altro corso di laurea non presente a pavia',
 'dopo aver discusso con i miei genitori pensiamo che io non sia adatto per questo corso ',
 "mancanza di interesse nell'iniziare un percorso formativo inerente alla facoltà di scienze biologiche ",
 'entrato in graduatoria unimi',
 'purtroppo il lavoro mi impedisce di andare avanti.',
 'ammissione ad un altro corso di laurea   verificare marca da bollo   marina',
 'prossima immatricolazione al corso di laurea in medicina e chirurgia  presso altro ateneo ',
 'frequentando il mio corso di laurea mi sono reso conto che non rispecchiava le mie aspettative personali, non riuscendomi ad appassionare ho deciso di fermarmi.',
 'incompatibilità del corso con i miei interessi ',
 'mancanza di tempo e volontà di cambiare facoltà',
 'iscrizione ad altra università',
 "ammissione e immatricolazione presso l'università statale di milano",
 "richiesta annullata d'ufficio, vedi fd n. \t1005908",
 'passata selezione concorso aa.mm. guardia di finanza',
 "cambio facoltà presso un'altra università, per motivi logistici",
 'ammissione in un altro ateneo ',
 'iscrizione ad altro corso universitario',
 'voglio prendere tempo per ponderare meglio la mia scelta.',
 'scelta di una nuova facoltà ',
 'in questo momento non riesco a conciliare studio e lavoro.',
 'ho constatato che non è il percorso di studi più adatto a me',
 "frequentazione di un'altra università",
 "con immenso rammarico, presento la rinuncia agli studi, poichè nel frattempo sono salita in graduatoria in un altro corso presso un'altra università, il quale personalmente rispecchia più le mie esigenze. ",
 'ammissione in un altra università più vicina a casa',
 'ho preferito la facoltà di biotecnologie di una città più vicino alla mia',
 "sono entrata presso l'università d milano-bicocca e mi sono immatricolata. ",
 'cambio facoltà e ateneo ',
 'immatricolazione presso altro ateneo per facoltà di medicina ',
 'sono entrata a medicina!',
 'unfortunately due to some covid complications and health issues of mine and my family, i will not be able to join this intake. \ntherefore i request you to please consider my request to cancel my enrollment. as this time is very critical for me, any financial help will give assistance to my family. so kind request to please coordinate for reimbursement of enrollment fee and i shall be grateful to you.\n\nthank you',
 "causa problemi familiari, sono impossibilitata a intraprendere il percorso di studi nella città di pavia. al momento dell'immatricolazione non erano previsti cambiamenti di tale natura.",
 'incapacità di lavorare e studiare contemporaneamente, oltre che alle tasse universitarie troppo alte ',
 'motivi di salute- passaggio ad una facoltà più vicina alla residenza ',
 'problemi di salute ',
 'motivi di salute',
 'motivi personali di spostamento.',
 'cambio facoltà e ateneo ',
 "presento una richiesta di rinuncia agli studi presso l'università di pavia, in quanto esigenze lavorative e personali mi hanno costretto a trasferirmi e a proseguire gli studi altrove. ",
 'troppi impegni lavorativi, mi riaffaccerò al mondo universitario con più consapevolezza una volta che avrò assestato la mia condizione di vita e lavorativa.',
 'desidero cambiare facoltà ',
 'ammessa in un altro ateneo',
 'ho trovato lavoro',
 'cambio sede universitaria',
 'iscrizione altra univesità ',
 "ammissione al corso di medicina e chirurgia presso l'università di torino",
 'livello di difficoltà troppo elevato.',
 'immatricolazione presso altro ateneo.',
 'intenzionata ad iscrivermi verso altro ateneo',
 'ammissione università statale di milano',
 "immatricolazione in un'altra università",
 'due to scholarship rejection from edisu pavia (i belong to middle class in my country, but family\x92s income is still not enough to afford), i am unable to afford my education and living expenses in italy.',
 'non mi sento totalmente adeguata e preparata per questo percorso.',
 'amissione a un altro corso di studi',
 'possibility to enroll in another course',
 'dear sir / madam,\nfirst of all, i would like to thank you for the position you offered me in the postgraduate course \x93msc psychology, neuroscience and human sciences\x94. it was my honor to be among the successful applicants. however, due to personal issues -mainly financial problems- i have to stay in greece and support my family. therefore, i have to postpone my education for a while and withdraw from the position. i wanted to inform you as soon as possible so you can pass this prevalence to someone else. if life allows, our paths may cross again in the future. \n\nyours faithfully,\nsinis christos ',
 'sono stata ammessa alla facoltà di medicina e chirurgia ',
 'iscrizione ad un altro corso di studi',
 'iscrizione al corso di laurea in medicina e chirurgia',
 'necessità di iscrizione alla stessa facoltà in un altro ateneo.',
 "ho deciso di intraprendere un nuovo percorso, il quale non comprende la frequentazione dell'università o lo studio ",
 'cambio corso di studi ',
 "rinuncia per poter terminare la carriera ed iscrivermi all'università degli studi di milano bicocca, che si trova a una distanza minore dalla mia residenza.",
 'cambio corso l\x92anno prossimo ',
 'incompatibilità con i miei progetti futuri.',
 'superamento test di medicina e chirurgia 2021 e immatricolazione alla facoltà di medicina. ',
 'sono entrata all\x92università della mia città cioè brescia ',
 'ho trovato un posto di lavoro',
 'cambio di università ',
 "iscrizione odontoiatria all'universita' di milano",
 'il percorso di studi non è coerente con le mie prospettive di vita future e dunque non ha stimolato il mio interesse in esso.',
 'cambio corso di laurea',
 'iscrizione in un\x92altro ateneo',
 'perseguimento di altra carriera',
 "non riesco a frequentare l'università per motivi di lavoro ",
 'non gradimento del corso',
 'corso non in linea con le aspettative dello studente',
 "scelta di dedicarsi all'attività lavorativa. ",
 'perché mi sono reso conto che non è la facoltà più idonea per me. ',
 'cambio di corso e ateneo ',
 "impossibilità a seguire lezioni e mancato interesse in quest'ultime",
 "non mi sono trovata bene e ho avuto molte difficoltà per quanto riguarda non solo la didattica ma anche l'organizzazione della scuola ma soprattutto della segreteria  ",
 'rinuncio agli studi perchè non sono più interessata a questo corso di studi',
 "immatricolazione in un'altra universita' (medesima facoltà)",
 'salve, \nsono una lavoratrice full time e per una nuova opportunità lavorativa non riesco a seguire i corsi e gestire la necessaria preparazione agli esami.\nvi ringrazio per la gentilezza dimostrata.\n\ncordiali saluti,\nsantini jessica',
 'immatricolazione presso facoltà e università differenti per motivi di distanza e di interessi.',
 'difficoltà a completare il piano di studi ',
 "desidero iscrivermi a un'altra facoltà.",
 'corso troppo pesante',
 "vado in un'altra università ",
 'rinuncia volontaria degli studi',
 'cambio ambito di studi',
 'sono interessato in un cambio di corso',
 'scelta sbagliata della corso di laurea ',
 'impossibilità a continuare gli studi per motivi economici. ',
 'impossibilità di continuare gli studi a causa lavorativa.',
 'il corso non mi ha suscitato l\x92interesse e la passione che credevo di possedere.',
 "immatricolazione primo anno all'università di medicina",
 'cambio corso di laurea e ateneo',
 "ripresa degli studi il prossimo anno ad altra universita'",
 'motivi di famiglia',
 'ammissione ad un altro corso di laurea ad accesso programmato.',
 'mancata assegnazione alloggio ',
 'nel tempo ho capito che questo percorso di studi non mi appaga e non è probabilmente la mia strada. ',
 "il motivo è che mi hanno preso in un'altra università a lombardia. ",
 'cambio facoltà e università',
 'intraprendere il percorso di studi in una città più vicina alla mia residenza ',
 'cambio di facoltà.',
 'non più interessato al corso',
 'trasferimento in università più vicina al domicilio',
 'trasferimento presso altro ateneo',
 'voglio iscrivermi ad un altro corso di laurea',
 'immatricolazione presso altro ateneo nel corso di prima scelta',
 'immatricolazione presso un altro ateneo',
 'cambio di corso',
 'cambio indirizzi di studi',
 'scelta di università differente',
 'iscrizione ad altra facoltà in un altro ateneo',
 'possibilità di immatricolazione a corso di studio con programmazione nazionale degli accessi (medicina e chirurgia) ',
 'volontà di cambiare università',
 'cambiamento della scelta universitaria ',
 'iscrizione ad altro ateneo',
 'passaggio di corso ',
 'ingresso nel mondo del lavoro. ',
 'iscrizione ad un altro ateneo',
 "presento la rinuncia agli studi per motivi personali. ho deciso di non proseguire gli studi, preferendo avvicinarmi già da subito al mondo del lavoro, dato che mi si è presentata tale oppurtunità. di conseguenza avendo un lavoro full time trovo difficile continuare a frequentare l'università nello stesso momento, ciò conferma dal fatto che non ho mai partecipato alle lezioni e non ho sostenuto nessun esame.",
 'gravi motivi familiari',
 'immatricolazione a nuova carriera in diverso ateneo',
 'ripescaggio in un altro ateneo',
 'a seguiro del primo semestre di università e dep periodo di studio preparatorio per gli esami ho trovato le materie poco stimolanti prendendo atto degli scarsi rendimenti e della fatica riscontrata nello studio ho deciso di rinunciare agli studi',
 'trasferimento presso università degli studi di novara',
 "necessità di immatricolarmi alla facoltà di medicina presso l'ateneo di ferrara",
 'rinuncia agli studi ',
 "cambiare facolta' perche' ho capito che il percorso di studio non fa per me",
 'immatricolazione presso altra università',
 'passaggio ad altro corso di studi',
 'iscrizione ad altra università ',
 'perdita di interesse',
 'cambio di facoltà',
 'immatricolazione in un altro ateneo ',
 'rinuncia compiuta a causa di un cambio volontario di facoltà universitaria.',
 'iscrizione a altro ateneo ',
 'impossibilità di trasferimento a pavia per questioni famigliari.',
 'preferisco non specificare.',
 "ammissione al corso di studio in farmacia presso l'università di brescia, città nella quale risiedo.",
 "richiedo la rinuncia agli studi presso l'università di pavia perché ho deciso di cambiare facoltà universitaria. ",
 'impossibilità di pagare le tasse universitarie, vista la dichiarazione di studente non indipendente mi è stato associato il massimo delle tasse',
 'non più interesse all\x92indirizzo. ',
 'corso non idoneo per la mia vita',
 'i am no longer interested in the ma degree in "the ancient mediterranean world". i have a full-time job and career. thank you for your understanding.',
 'iscrizione ad altro ateneo.',
 'sospensione studi causa motivi familiari e successiva ripresa negli anni che seguono.',

In [4]:
from sentence_transformers import SentenceTransformer
#https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v2

# Modello BERT multilingue - uno dei più usati
model_name = "sentence-transformers/distiluse-base-multilingual-cased-v2"
sbert = SentenceTransformer(model_name)

# Calcolo embedding con sbert https://www.sbert.net/
embeddings = sbert.encode(texts, show_progress_bar=True)
print("Shape embeddings:", embeddings.shape)

C:\Users\Utente\PycharmProjects\Data_mining_UPO\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WARNING:tensorflow:From C:\Users\Utente\PycharmProjects\Data_mining_UPO\.venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Batches: 100%|██████████| 70/70 [00:30<00:00,  2.26it/s]

Shape embeddings: (2237, 512)

In [5]:
print(embeddings.shape)   # (numero_testi, 512)
print(embeddings[0][:10]) # primi 10 valori del primo embedding

(2237, 512)
[-3.3089500e-02  3.5384533e-03  1.0899307e-02  1.6114295e-02
  7.6892860e-02 -4.2174044e-03  2.4098786e-02 -2.2410324e-02
 -2.2858584e-03  4.2111147e-05]

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
# esempio che da provare che c'è su github
sim = cosine_similarity([embeddings[0]], [embeddings[1]])
print("Similarità tra frase 0 e frase 1:", sim[0][0])

Similarità tra frase 0 e frase 1: 0.27793556

In [1]:
import requests

url = "https://raw.githubusercontent.com/stopwords-iso/stopwords-it/master/stopwords-it.txt"
response = requests.get(url)

stopwords_italiane = set(response.text.splitlines())
print(len(stopwords_italiane))

632

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
# faccio un listino aggiuntivo di stopwords che i modelli non colgono (i dont know why)
#custom_stopwords = ["non", "ho", "di", "per", "la", "il", "in", "al", "un", "una"]
vectorizer_model = CountVectorizer(stop_words=stopwords_italiane)

from bertopic import BERTopic
# https://maartengr.github.io/BERTopic/index.html#common
topic_model = BERTopic(language="italian",
                       embedding_model=sbert,
                       vectorizer_model=vectorizer_model,
                       # momento divertimento con i params :)
                       # metto nr_topics iperparam perchè se lancio così il modello genera 50+ topics
                       #nr_topics=5,
                       min_topic_size=50,
                       # se un giorno volessi semplificare tutto basta mettere il sentence trasformer qui
                       n_gram_range=(1, 2) #usa tutte le sequenze da 1, 2 parole come possibili keyword dei topic
)
topics, probs = topic_model.fit_transform(texts, embeddings)

# Assegna topics al dataframe
df["topics"] = topics
#df.to_csv("rinunce_topics3.csv", index=False)

# Report rapido
topic_info = topic_model.get_topic_info()
print(topic_info.head())

   Topic  Count                                        Name  \
0     -1    256               -1_inizio_salute_studi_milano
1      0    752               0_studi_percorso_corso_deciso
2      1    428  1_altra_iscrizione_ateneo_immatricolazione
3      2    323     2_motivi_impossibilità_lavoro_personali
4      3    236           3_cambio_facoltà_corso_università

                                      Representation  \
0  [inizio, salute, studi, milano, problemi, moti...
1  [studi, percorso, corso, deciso, to, universit...
2  [altra, iscrizione, ateneo, immatricolazione, ...
3  [motivi, impossibilità, lavoro, personali, lav...
4  [cambio, facoltà, corso, università, studi, ca...

                                 Representative_Docs
0  [problemi di salute, rinuncia per motivi di sa...
1  [ho deciso di intraprendere un altro percorso ...
2  [iscrizione presso un'altra università, iscriz...
3  [impossibilità nel proseguire con gli studi pe...
4  [cambio di corso, cambio del corso , cambio di...

In [9]:
# il -1 è il cluster degli outliers
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,256,-1_inizio_salute_studi_milano,"[inizio, salute, studi, milano, problemi, moti...","[problemi di salute, rinuncia per motivi di sa..."
1,0,752,0_studi_percorso_corso_deciso,"[studi, percorso, corso, deciso, to, universit...",[ho deciso di intraprendere un altro percorso ...
2,1,428,1_altra_iscrizione_ateneo_immatricolazione,"[altra, iscrizione, ateneo, immatricolazione, ...","[iscrizione presso un'altra università, iscriz..."
3,2,323,2_motivi_impossibilità_lavoro_personali,"[motivi, impossibilità, lavoro, personali, lav...",[impossibilità nel proseguire con gli studi pe...
4,3,236,3_cambio_facoltà_corso_università,"[cambio, facoltà, corso, università, studi, ca...","[cambio di corso, cambio del corso , cambio di..."
5,4,94,4_scelta_sbagliata_percorso_sbagliato,"[scelta, sbagliata, percorso, sbagliato, studi...","[scelta di un altro percorso, scelta altro per..."
6,5,85,5_medicina_chirurgia_facoltà_presso,"[medicina, chirurgia, facoltà, presso, immatri...",[immatricolazione a medicina e chirurgia press...
7,6,63,6_trasferimento_ateneo_passaggio_presso,"[trasferimento, ateneo, passaggio, presso, alt...","[trasferimento ad un altro ateneo, trasferimen..."

In [10]:
topic_model.get_topic_freq()

   Topic  Count
3      0    752
4      1    428
0      2    323
2     -1    256
1      3    236
5      4     94
6      5     85
7      6     63

In [11]:
topic_model.generate_topic_labels()

['-1_inizio_salute_studi',
 '0_studi_percorso_corso',
 '1_altra_iscrizione_ateneo',
 '2_motivi_impossibilità_lavoro',
 '3_cambio_facoltà_corso',
 '4_scelta_sbagliata_percorso',
 '5_medicina_chirurgia_facoltà',
 '6_trasferimento_ateneo_passaggio']

In [12]:
topic_model.get_params()

# questo modello usa di default HDBSCAN per clusterizzare i topic dopo l'embedding!

{'calculate_probabilities': False,
 'ctfidf_model': ClassTfidfTransformer(),
 'embedding_model': <bertopic.backend._sentencetransformers.SentenceTransformerBackend at 0x183b062af10>,
 'hdbscan_model': HDBSCAN(min_cluster_size=50, prediction_data=True),
 'language': None,
 'low_memory': False,
 'min_topic_size': 50,
 'n_gram_range': (1, 2),
 'nr_topics': None,
 'representation_model': None,
 'seed_topic_list': None,
 'top_n_words': 10,
 'umap_model': UMAP(angular_rp_forest=True, low_memory=False, metric='cosine', min_dist=0.0, n_components=5, tqdm_kwds={'bar_format': '{desc}: {percentage:3.0f}%| {bar} {n_fmt}/{total_fmt} [{elapsed}]', 'desc': 'Epochs completed', 'disable': True}),
 'vectorizer_model': CountVectorizer(stop_words=['a', 'abbastanza', 'abbia', 'abbiamo', 'abbiano',
                             'abbiate', 'accidenti', 'ad', 'adesso', 'affinché',
                             'agl', 'agli', 'ahime', 'ahimè', 'ai', 'al',
                             'alcuna', 'alcuni', 'alcuno', 'all', 'alla', 'alle',
                             'allo', 'allora', 'altre', 'altri', 'altrimenti',
                             'altro', 'altrove', 'altrui', ...]),
 'verbose': False,
 'zeroshot_min_similarity': 0.7,
 'zeroshot_topic_list': None}

In [13]:
topic_model.visualize_topics()

In [14]:
topic_model.get_representative_docs()

{-1: ['problemi di salute',
  'rinuncia per motivi di salute',
  'immatricolazione presso università degli studi di milano.'],
 0: ['ho deciso di intraprendere un altro percorso di studi',
  'ho deciso di non proseguire il corso dei miei studi',
  "ho deciso di intraprendere un altro percorso di studi in un'altra università"],
 1: ["iscrizione presso un'altra università",
  'iscrizione presso altra università',
  "iscrizione presso un altro corso di laurea di un'altra università"],
 2: ['impossibilità nel proseguire con gli studi per motivi personali.',
  'impossibilità a proseguire gli studi per motivi personali',
  'motivi personali. ho trovato lavoro'],
 3: ['cambio di corso', 'cambio del corso ', 'cambio di corso'],
 4: ['scelta di un altro percorso',
  'scelta altro percorso di studi ',
  'scelta altro corso'],
 5: ['immatricolazione a medicina e chirurgia presso altro ateneo',
  'immatricolazione alla facoltà di medicina e chirurgia presso un altro ateneo.',
  'iscrizione alla facoltà di medicina e chirurgia'],
 6: ['trasferimento ad un altro ateneo',
  'trasferimento ad altro ateneo.',
  'trasferimento altro ateneo']}

In [15]:
#df.to_csv("rinunce_topics3.csv", index=False)